CREATE TABLE usuarios (
 id_usuario INT PRIMARY KEY AUTO_INCREMENT,
 apelido VARCHAR(50) NOT NULL,
 senha VARCHAR(60) NOT NULL,
 email VARCHAR(255) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 deleted_at DATETIME NOT NULL
)